#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Management_System
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TravelDatabase")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUserInfo(UserInfo instance);
    partial void UpdateUserInfo(UserInfo instance);
    partial void DeleteUserInfo(UserInfo instance);
    partial void InsertTour_booking(Tour_booking instance);
    partial void UpdateTour_booking(Tour_booking instance);
    partial void DeleteTour_booking(Tour_booking instance);
    partial void InsertTOUR(TOUR instance);
    partial void UpdateTOUR(TOUR instance);
    partial void DeleteTOUR(TOUR instance);
    partial void InsertHOTEL(HOTEL instance);
    partial void UpdateHOTEL(HOTEL instance);
    partial void DeleteHOTEL(HOTEL instance);
    partial void InsertHOTEL_BOOKING(HOTEL_BOOKING instance);
    partial void UpdateHOTEL_BOOKING(HOTEL_BOOKING instance);
    partial void DeleteHOTEL_BOOKING(HOTEL_BOOKING instance);
    partial void InsertAdminTable(AdminTable instance);
    partial void UpdateAdminTable(AdminTable instance);
    partial void DeleteAdminTable(AdminTable instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TravelDatabaseConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UserInfo> UserInfos
		{
			get
			{
				return this.GetTable<UserInfo>();
			}
		}
		
		public System.Data.Linq.Table<Tour_booking> Tour_bookings
		{
			get
			{
				return this.GetTable<Tour_booking>();
			}
		}
		
		public System.Data.Linq.Table<TOUR> TOURs
		{
			get
			{
				return this.GetTable<TOUR>();
			}
		}
		
		public System.Data.Linq.Table<HOTEL> HOTELs
		{
			get
			{
				return this.GetTable<HOTEL>();
			}
		}
		
		public System.Data.Linq.Table<HOTEL_BOOKING> HOTEL_BOOKINGs
		{
			get
			{
				return this.GetTable<HOTEL_BOOKING>();
			}
		}
		
		public System.Data.Linq.Table<AdminTable> AdminTables
		{
			get
			{
				return this.GetTable<AdminTable>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserInfo")]
	public partial class UserInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Email;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Gender;
		
		private string _Password;
		
		private System.DateTime _dob;
		
		private string _Street;
		
		private string _City;
		
		private string _State;
		
		private EntitySet<Tour_booking> _Tour_bookings;
		
		private EntityRef<HOTEL_BOOKING> _HOTEL_BOOKING;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OndobChanging(System.DateTime value);
    partial void OndobChanged();
    partial void OnStreetChanging(string value);
    partial void OnStreetChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    #endregion
		
		public UserInfo()
		{
			this._Tour_bookings = new EntitySet<Tour_booking>(new Action<Tour_booking>(this.attach_Tour_bookings), new Action<Tour_booking>(this.detach_Tour_bookings));
			this._HOTEL_BOOKING = default(EntityRef<HOTEL_BOOKING>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dob", DbType="Date NOT NULL")]
		public System.DateTime dob
		{
			get
			{
				return this._dob;
			}
			set
			{
				if ((this._dob != value))
				{
					this.OndobChanging(value);
					this.SendPropertyChanging();
					this._dob = value;
					this.SendPropertyChanged("dob");
					this.OndobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				if ((this._Street != value))
				{
					this.OnStreetChanging(value);
					this.SendPropertyChanging();
					this._Street = value;
					this.SendPropertyChanged("Street");
					this.OnStreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserInfo_Tour_booking", Storage="_Tour_bookings", ThisKey="Email", OtherKey="Email")]
		public EntitySet<Tour_booking> Tour_bookings
		{
			get
			{
				return this._Tour_bookings;
			}
			set
			{
				this._Tour_bookings.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserInfo_HOTEL_BOOKING", Storage="_HOTEL_BOOKING", ThisKey="Email", OtherKey="Email", IsUnique=true, IsForeignKey=false)]
		public HOTEL_BOOKING HOTEL_BOOKING
		{
			get
			{
				return this._HOTEL_BOOKING.Entity;
			}
			set
			{
				HOTEL_BOOKING previousValue = this._HOTEL_BOOKING.Entity;
				if (((previousValue != value) 
							|| (this._HOTEL_BOOKING.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOTEL_BOOKING.Entity = null;
						previousValue.UserInfo = null;
					}
					this._HOTEL_BOOKING.Entity = value;
					if ((value != null))
					{
						value.UserInfo = this;
					}
					this.SendPropertyChanged("HOTEL_BOOKING");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tour_bookings(Tour_booking entity)
		{
			this.SendPropertyChanging();
			entity.UserInfo = this;
		}
		
		private void detach_Tour_bookings(Tour_booking entity)
		{
			this.SendPropertyChanging();
			entity.UserInfo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tour_booking")]
	public partial class Tour_booking : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Booking_id;
		
		private string _Email;
		
		private decimal _Tour_id;
		
		private int _No_of_persons;
		
		private EntityRef<UserInfo> _UserInfo;
		
		private EntityRef<TOUR> _TOUR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBooking_idChanging(int value);
    partial void OnBooking_idChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTour_idChanging(decimal value);
    partial void OnTour_idChanged();
    partial void OnNo_of_personsChanging(int value);
    partial void OnNo_of_personsChanged();
    #endregion
		
		public Tour_booking()
		{
			this._UserInfo = default(EntityRef<UserInfo>);
			this._TOUR = default(EntityRef<TOUR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Booking_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Booking_id
		{
			get
			{
				return this._Booking_id;
			}
			set
			{
				if ((this._Booking_id != value))
				{
					this.OnBooking_idChanging(value);
					this.SendPropertyChanging();
					this._Booking_id = value;
					this.SendPropertyChanged("Booking_id");
					this.OnBooking_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					if (this._UserInfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tour_id", DbType="Decimal(2,0) NOT NULL")]
		public decimal Tour_id
		{
			get
			{
				return this._Tour_id;
			}
			set
			{
				if ((this._Tour_id != value))
				{
					if (this._TOUR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTour_idChanging(value);
					this.SendPropertyChanging();
					this._Tour_id = value;
					this.SendPropertyChanged("Tour_id");
					this.OnTour_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_of_persons", DbType="Int NOT NULL")]
		public int No_of_persons
		{
			get
			{
				return this._No_of_persons;
			}
			set
			{
				if ((this._No_of_persons != value))
				{
					this.OnNo_of_personsChanging(value);
					this.SendPropertyChanging();
					this._No_of_persons = value;
					this.SendPropertyChanged("No_of_persons");
					this.OnNo_of_personsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserInfo_Tour_booking", Storage="_UserInfo", ThisKey="Email", OtherKey="Email", IsForeignKey=true)]
		public UserInfo UserInfo
		{
			get
			{
				return this._UserInfo.Entity;
			}
			set
			{
				UserInfo previousValue = this._UserInfo.Entity;
				if (((previousValue != value) 
							|| (this._UserInfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UserInfo.Entity = null;
						previousValue.Tour_bookings.Remove(this);
					}
					this._UserInfo.Entity = value;
					if ((value != null))
					{
						value.Tour_bookings.Add(this);
						this._Email = value.Email;
					}
					else
					{
						this._Email = default(string);
					}
					this.SendPropertyChanged("UserInfo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_Tour_booking", Storage="_TOUR", ThisKey="Tour_id", OtherKey="TOUR_ID", IsForeignKey=true)]
		public TOUR TOUR
		{
			get
			{
				return this._TOUR.Entity;
			}
			set
			{
				TOUR previousValue = this._TOUR.Entity;
				if (((previousValue != value) 
							|| (this._TOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TOUR.Entity = null;
						previousValue.Tour_bookings.Remove(this);
					}
					this._TOUR.Entity = value;
					if ((value != null))
					{
						value.Tour_bookings.Add(this);
						this._Tour_id = value.TOUR_ID;
					}
					else
					{
						this._Tour_id = default(decimal);
					}
					this.SendPropertyChanged("TOUR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TOURS")]
	public partial class TOUR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _TOUR_ID;
		
		private string _TOUR_NAME;
		
		private string _PLACE;
		
		private decimal _DAYS;
		
		private decimal _PRICE;
		
		private string _LOCATIONS;
		
		private string _TOUR_INFO;
		
		private EntitySet<Tour_booking> _Tour_bookings;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTOUR_IDChanging(decimal value);
    partial void OnTOUR_IDChanged();
    partial void OnTOUR_NAMEChanging(string value);
    partial void OnTOUR_NAMEChanged();
    partial void OnPLACEChanging(string value);
    partial void OnPLACEChanged();
    partial void OnDAYSChanging(decimal value);
    partial void OnDAYSChanged();
    partial void OnPRICEChanging(decimal value);
    partial void OnPRICEChanged();
    partial void OnLOCATIONSChanging(string value);
    partial void OnLOCATIONSChanged();
    partial void OnTOUR_INFOChanging(string value);
    partial void OnTOUR_INFOChanged();
    #endregion
		
		public TOUR()
		{
			this._Tour_bookings = new EntitySet<Tour_booking>(new Action<Tour_booking>(this.attach_Tour_bookings), new Action<Tour_booking>(this.detach_Tour_bookings));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_ID", DbType="Decimal(2,0) NOT NULL", IsPrimaryKey=true)]
		public decimal TOUR_ID
		{
			get
			{
				return this._TOUR_ID;
			}
			set
			{
				if ((this._TOUR_ID != value))
				{
					this.OnTOUR_IDChanging(value);
					this.SendPropertyChanging();
					this._TOUR_ID = value;
					this.SendPropertyChanged("TOUR_ID");
					this.OnTOUR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_NAME", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TOUR_NAME
		{
			get
			{
				return this._TOUR_NAME;
			}
			set
			{
				if ((this._TOUR_NAME != value))
				{
					this.OnTOUR_NAMEChanging(value);
					this.SendPropertyChanging();
					this._TOUR_NAME = value;
					this.SendPropertyChanged("TOUR_NAME");
					this.OnTOUR_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLACE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string PLACE
		{
			get
			{
				return this._PLACE;
			}
			set
			{
				if ((this._PLACE != value))
				{
					this.OnPLACEChanging(value);
					this.SendPropertyChanging();
					this._PLACE = value;
					this.SendPropertyChanged("PLACE");
					this.OnPLACEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAYS", DbType="Decimal(2,0) NOT NULL")]
		public decimal DAYS
		{
			get
			{
				return this._DAYS;
			}
			set
			{
				if ((this._DAYS != value))
				{
					this.OnDAYSChanging(value);
					this.SendPropertyChanging();
					this._DAYS = value;
					this.SendPropertyChanged("DAYS");
					this.OnDAYSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Decimal(6,0) NOT NULL")]
		public decimal PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this.OnPRICEChanging(value);
					this.SendPropertyChanging();
					this._PRICE = value;
					this.SendPropertyChanged("PRICE");
					this.OnPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATIONS", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string LOCATIONS
		{
			get
			{
				return this._LOCATIONS;
			}
			set
			{
				if ((this._LOCATIONS != value))
				{
					this.OnLOCATIONSChanging(value);
					this.SendPropertyChanging();
					this._LOCATIONS = value;
					this.SendPropertyChanged("LOCATIONS");
					this.OnLOCATIONSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_INFO", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string TOUR_INFO
		{
			get
			{
				return this._TOUR_INFO;
			}
			set
			{
				if ((this._TOUR_INFO != value))
				{
					this.OnTOUR_INFOChanging(value);
					this.SendPropertyChanging();
					this._TOUR_INFO = value;
					this.SendPropertyChanged("TOUR_INFO");
					this.OnTOUR_INFOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_Tour_booking", Storage="_Tour_bookings", ThisKey="TOUR_ID", OtherKey="Tour_id")]
		public EntitySet<Tour_booking> Tour_bookings
		{
			get
			{
				return this._Tour_bookings;
			}
			set
			{
				this._Tour_bookings.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tour_bookings(Tour_booking entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = this;
		}
		
		private void detach_Tour_bookings(Tour_booking entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOTELS")]
	public partial class HOTEL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _HOTEL_ID;
		
		private string _HOTEL_NAME;
		
		private string _STREET;
		
		private string _CITY;
		
		private string _STATE;
		
		private System.Nullable<decimal> _PHONE1;
		
		private System.Nullable<decimal> _PHONE2;
		
		private System.Nullable<decimal> _ROOM_COST;
		
		private EntitySet<HOTEL_BOOKING> _HOTEL_BOOKINGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHOTEL_IDChanging(decimal value);
    partial void OnHOTEL_IDChanged();
    partial void OnHOTEL_NAMEChanging(string value);
    partial void OnHOTEL_NAMEChanged();
    partial void OnSTREETChanging(string value);
    partial void OnSTREETChanged();
    partial void OnCITYChanging(string value);
    partial void OnCITYChanged();
    partial void OnSTATEChanging(string value);
    partial void OnSTATEChanged();
    partial void OnPHONE1Changing(System.Nullable<decimal> value);
    partial void OnPHONE1Changed();
    partial void OnPHONE2Changing(System.Nullable<decimal> value);
    partial void OnPHONE2Changed();
    partial void OnROOM_COSTChanging(System.Nullable<decimal> value);
    partial void OnROOM_COSTChanged();
    #endregion
		
		public HOTEL()
		{
			this._HOTEL_BOOKINGs = new EntitySet<HOTEL_BOOKING>(new Action<HOTEL_BOOKING>(this.attach_HOTEL_BOOKINGs), new Action<HOTEL_BOOKING>(this.detach_HOTEL_BOOKINGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEL_ID", DbType="Decimal(2,0) NOT NULL", IsPrimaryKey=true)]
		public decimal HOTEL_ID
		{
			get
			{
				return this._HOTEL_ID;
			}
			set
			{
				if ((this._HOTEL_ID != value))
				{
					this.OnHOTEL_IDChanging(value);
					this.SendPropertyChanging();
					this._HOTEL_ID = value;
					this.SendPropertyChanged("HOTEL_ID");
					this.OnHOTEL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEL_NAME", DbType="VarChar(20)")]
		public string HOTEL_NAME
		{
			get
			{
				return this._HOTEL_NAME;
			}
			set
			{
				if ((this._HOTEL_NAME != value))
				{
					this.OnHOTEL_NAMEChanging(value);
					this.SendPropertyChanging();
					this._HOTEL_NAME = value;
					this.SendPropertyChanged("HOTEL_NAME");
					this.OnHOTEL_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STREET", DbType="VarChar(20)")]
		public string STREET
		{
			get
			{
				return this._STREET;
			}
			set
			{
				if ((this._STREET != value))
				{
					this.OnSTREETChanging(value);
					this.SendPropertyChanging();
					this._STREET = value;
					this.SendPropertyChanged("STREET");
					this.OnSTREETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="VarChar(10)")]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this.OnCITYChanging(value);
					this.SendPropertyChanging();
					this._CITY = value;
					this.SendPropertyChanged("CITY");
					this.OnCITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE", DbType="VarChar(15)")]
		public string STATE
		{
			get
			{
				return this._STATE;
			}
			set
			{
				if ((this._STATE != value))
				{
					this.OnSTATEChanging(value);
					this.SendPropertyChanging();
					this._STATE = value;
					this.SendPropertyChanged("STATE");
					this.OnSTATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE1", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> PHONE1
		{
			get
			{
				return this._PHONE1;
			}
			set
			{
				if ((this._PHONE1 != value))
				{
					this.OnPHONE1Changing(value);
					this.SendPropertyChanging();
					this._PHONE1 = value;
					this.SendPropertyChanged("PHONE1");
					this.OnPHONE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE2", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> PHONE2
		{
			get
			{
				return this._PHONE2;
			}
			set
			{
				if ((this._PHONE2 != value))
				{
					this.OnPHONE2Changing(value);
					this.SendPropertyChanging();
					this._PHONE2 = value;
					this.SendPropertyChanged("PHONE2");
					this.OnPHONE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_COST", DbType="Decimal(5,0)")]
		public System.Nullable<decimal> ROOM_COST
		{
			get
			{
				return this._ROOM_COST;
			}
			set
			{
				if ((this._ROOM_COST != value))
				{
					this.OnROOM_COSTChanging(value);
					this.SendPropertyChanging();
					this._ROOM_COST = value;
					this.SendPropertyChanged("ROOM_COST");
					this.OnROOM_COSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOTEL_HOTEL_BOOKING", Storage="_HOTEL_BOOKINGs", ThisKey="HOTEL_ID", OtherKey="HOTEL_ID")]
		public EntitySet<HOTEL_BOOKING> HOTEL_BOOKINGs
		{
			get
			{
				return this._HOTEL_BOOKINGs;
			}
			set
			{
				this._HOTEL_BOOKINGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOTEL_BOOKINGs(HOTEL_BOOKING entity)
		{
			this.SendPropertyChanging();
			entity.HOTEL = this;
		}
		
		private void detach_HOTEL_BOOKINGs(HOTEL_BOOKING entity)
		{
			this.SendPropertyChanging();
			entity.HOTEL = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOTEL_BOOKING")]
	public partial class HOTEL_BOOKING : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Email;
		
		private decimal _HOTEL_ID;
		
		private decimal _PERSONS;
		
		private EntityRef<HOTEL> _HOTEL;
		
		private EntityRef<UserInfo> _UserInfo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnHOTEL_IDChanging(decimal value);
    partial void OnHOTEL_IDChanged();
    partial void OnPERSONSChanging(decimal value);
    partial void OnPERSONSChanged();
    #endregion
		
		public HOTEL_BOOKING()
		{
			this._HOTEL = default(EntityRef<HOTEL>);
			this._UserInfo = default(EntityRef<UserInfo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					if (this._UserInfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEL_ID", DbType="Decimal(2,0) NOT NULL")]
		public decimal HOTEL_ID
		{
			get
			{
				return this._HOTEL_ID;
			}
			set
			{
				if ((this._HOTEL_ID != value))
				{
					if (this._HOTEL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHOTEL_IDChanging(value);
					this.SendPropertyChanging();
					this._HOTEL_ID = value;
					this.SendPropertyChanged("HOTEL_ID");
					this.OnHOTEL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERSONS", DbType="Decimal(3,0) NOT NULL")]
		public decimal PERSONS
		{
			get
			{
				return this._PERSONS;
			}
			set
			{
				if ((this._PERSONS != value))
				{
					this.OnPERSONSChanging(value);
					this.SendPropertyChanging();
					this._PERSONS = value;
					this.SendPropertyChanged("PERSONS");
					this.OnPERSONSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOTEL_HOTEL_BOOKING", Storage="_HOTEL", ThisKey="HOTEL_ID", OtherKey="HOTEL_ID", IsForeignKey=true)]
		public HOTEL HOTEL
		{
			get
			{
				return this._HOTEL.Entity;
			}
			set
			{
				HOTEL previousValue = this._HOTEL.Entity;
				if (((previousValue != value) 
							|| (this._HOTEL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOTEL.Entity = null;
						previousValue.HOTEL_BOOKINGs.Remove(this);
					}
					this._HOTEL.Entity = value;
					if ((value != null))
					{
						value.HOTEL_BOOKINGs.Add(this);
						this._HOTEL_ID = value.HOTEL_ID;
					}
					else
					{
						this._HOTEL_ID = default(decimal);
					}
					this.SendPropertyChanged("HOTEL");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserInfo_HOTEL_BOOKING", Storage="_UserInfo", ThisKey="Email", OtherKey="Email", IsForeignKey=true)]
		public UserInfo UserInfo
		{
			get
			{
				return this._UserInfo.Entity;
			}
			set
			{
				UserInfo previousValue = this._UserInfo.Entity;
				if (((previousValue != value) 
							|| (this._UserInfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UserInfo.Entity = null;
						previousValue.HOTEL_BOOKING = null;
					}
					this._UserInfo.Entity = value;
					if ((value != null))
					{
						value.HOTEL_BOOKING = this;
						this._Email = value.Email;
					}
					else
					{
						this._Email = default(string);
					}
					this.SendPropertyChanged("UserInfo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdminTable")]
	public partial class AdminTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _username;
		
		private string _password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public AdminTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
